adding new module in HARFANGLAB -> Retrived agent hostname with their IP
SEKOIA-IO/automation-library pull request #1017
Opened 2024-07-04 13:44 UTC by lheronD

adding new module in harfanglab-> Retrived agent hostname with their IP.

It returns all agents with this IP address, along with their name, IP, last visit date, OS and status.

There's also a boolean button to select only the last agent in the list.

2024-07-19 07:42 UTC, soc-dstny commented
Hello, are you missing any information for the test workflow to be launched?

2024-07-19 14:21 UTC, soc-dstny approved these changes

2024-07-23 16:26 UTC, squioc requested changes
Hello.

Sorry for the delay.
We detected some issues in the action.
Can you fix them? Thank you

2024-07-23 16:26 UTC, squioc commented on HarfangLab/harfanglab/models.py
> +    os: str
According to the Harfanglab documentation,
the name of the date when the agent was last seen is `lastseen`.
With the property `os`, do you mean `ostype`?

First suggestion: Rename the properties (don't forget to rename the usage also)
```suggestion
    lastseen: str
    ostype: str
```

Second suggestion: Use Field's alias
```suggestion
    last_seen: str = Field(..., alias='lastseen')
    os: str = Field(..., alias='ostype'
```

2024-07-23 16:26 UTC, squioc commented on HarfangLab/harfanglab/get_hostnames_by_ip_action.py
> +        hostnames = [HostnameEntry(**entry) for entry in data]
The agents are returned to the `results` property from the response
```json
{
    "count": 2,
    "results": [...]
}
```

We suggest the following change
```suggestion
        hostnames = [HostnameEntry(**entry) for entry in data.get("results", [])]
```

2024-07-23 16:26 UTC, squioc commented on HarfangLab/action_harfanglab_gethostnamesbyip.json
> +        "type": "object"
According to the code, `hostnames` is a list of object

```suggestion
        "description": "Hostnames",
        "type": "array",
        "items": {
            "type": "object"
        }
```

2024-07-24 12:23 UTC, soc-dstny commented
I think the IC has gone through but the last check doesn't want to launch.

2024-07-26 07:51 UTC, squioc requested changes
Thank you for the changes.
Just a little fix to apply (and a suggestion).

Before I forget, can you also increase the number version in the [manifest.json](https://github.com/SEKOIA-IO/automation-library/blob/main/HarfangLab/manifest.json) file and add a little entry in the [CHANGELOG.md](https://github.com/SEKOIA-IO/automation-library/blob/main/HarfangLab/CHANGELOG.md)? Thank you

2024-07-26 07:51 UTC, squioc commented on HarfangLab/harfanglab/models.py
> +    ostype: str = Field(..., alias="ostype")
My bad. My previous comment was ambiguous.
As you renamed the fields like they are in the API response, you don't need to define an alias (Alias are useful when the name of the field in the model doesn't match the name of the field in the serialized structure)
I suggest removing the second part of the lines:
```suggestion
    lastseen: str
    ostype: str
```

2024-07-26 07:51 UTC, squioc commented on HarfangLab/harfanglab/get_hostnames_by_ip_action.py
> +        result = data.get("result") if isinstance(data, dict) else data
A little typo on the name of the field that contains the items in the API response:
```suggestion
        result = data.get("results") if isinstance(data, dict) else data
```

2024-07-31 06:53 UTC, squioc approved these changes
LGTM. Thanks for the contribution

2024-07-31 06:54 UTC, merged