Harfanglab download file from endpoint action
SEKOIA-IO/automation-library pull request #1129
Opened 2024-10-16 09:22 UTC by Godefroy-Amaury

Add the `action_harfanglab_download_file_from_endpoint` action.
Rely on the `downloadFile` job action.

2024-10-17 13:50 UTC, jeromefellus-sekoia reviewed
Looks great ! Thank you !

2024-10-17 14:24 UTC, jeromefellus-sekoia requested changes

2024-10-17 14:24 UTC, jeromefellus-sekoia commented on HarfangLab/harfanglab/job_executor.py
> +    def wait_for_job_completion(self) -> None:
```suggestion
    def wait_for_job_completion(self) -> None: # pragma: no cover
```

2024-10-17 14:56 UTC, squioc requested changes
Thanks for your contribution.

Some changes to apply:
- Can you increase the version number in the [manifest.json](https://github.com/SEKOIA-IO/automation-library/blob/main/HarfangLab/manifest.json) file?
- Can you add a new entry in the [CHANGELOG.md](https://github.com/SEKOIA-IO/automation-library/blob/main/HarfangLab/CHANGELOG.md) file?
Thank you.

2024-10-17 15:17 UTC, squioc requested changes

2024-10-17 15:17 UTC, squioc commented on HarfangLab/harfanglab/download_file_from_endpoint.py
> +        return self._artefact_info["sha256"]
When the file is not found, the `sha256` is undefined. Can you handle the case when the path to the file is incorrect or the download of the file failed?
Thanks

2024-10-17 15:17 UTC, squioc commented on HarfangLab/harfanglab/download_file_from_endpoint.py
> +        self._artefact_info = artefact_info
I suggest that the `download_status` property in the result of the job must be verified and raise an error if some wnet wrong.

2024-10-17 15:19 UTC, squioc commented on HarfangLab/manifest.json
> +  "version": "1.24",
We follow the [semver](https://semver.org/) convention for version number.
```suggestion
  "version": "1.24.0",
```

2024-10-17 15:20 UTC, squioc commented on HarfangLab/CHANGELOG.md
> +- Added functionality to download a file on endpoint
As you bump the version number, you can add it with the entry

```suggestion

## 2024-10-17 - 1.24.0

- Added functionality to download a file on endpoint
```

2024-10-17 15:29 UTC, squioc commented on HarfangLab/harfanglab/download_file_from_endpoint.py
> +        return self._artefact_info["sha256"]
Sample of the job response when the file is not found:

```json
{
  "count": 1,
  "next": null,
  "previous": null,
  "results": [
    {
      "shortname": "C:\\Users\\<REDACTED>\\Downloads\\hello.txt",
      "artefact_type": "downloaded file",
      "item_status": 0,
      "download_status": 1,
      "destination": "elastic",
      "job_id": "<REDACTED>",
      "@version": "1",
      "tenant": "<REDACTED>",
      "log_type": "investigation",
      "msg": "0 file(s) (0B) downloaded",
      "@timestamp": "2024-10-17T15:13:43.619423Z",
      "size": 0,
      "agent": {
        "ostype": "windows",
        "version": "4.1.6",
        "osversion": "10.0.22621",
        "osproducttype": "Windows 11 Pro",
        "domainname": "WORKGROUP",
        "agentid": "<REDACTED>",
        "hostname": "Windows11"
      },
      "date": "2024-10-17T15:13:42.975214Z",
      "job_instance_id": "<REDACTED>",
      "id": "<REDACTED>"
    }
  ],
  "filters": {
    "wildcard": [
      "artefact_type",
      "msg",
      "shortname",
      "longname",
      "agent.domainname",
      "agent.hostname",
      "agent.osproducttype"
    ]
  }
}
```

2024-10-17 16:34 UTC, jeromefellus-sekoia approved these changes

2024-10-24 10:24 UTC, squioc approved these changes
LGTM. Just a little change to apply to the README.md

2024-10-24 10:24 UTC, squioc commented on HarfangLab/CHANGELOG.md
> +- Added functionality to download a file on endpoint
```suggestion
## 2024-10-17 - 1.24.0

### Added

- Added functionality to download a file on endpoint
```

2024-10-24 10:25 UTC, squioc requested changes
A little change to apply in the README.md

2024-10-24 11:36 UTC, squioc approved these changes

2024-10-24 12:00 UTC, merged