add search module in AD
SEKOIA-IO/automation-library pull request #1146
Opened 2024-10-28 11:02 UTC by pbivic

2024-10-28 17:19 UTC, squioc requested changes
LGTM. A little change to apply in the definition of the action.

2024-10-28 17:19 UTC, squioc commented on MicrosoftActiveDirectory/action_search.json
> +        }
In order to express that the property can be nullable:
```suggestion
        "anyOf": [
          {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          {"type": "null"}
        ],
        "default": null
```

2024-10-28 17:30 UTC, TOUFIKIzakarya reviewed
Good job paul. Thanks for that.
just a little remark about tests

2024-10-28 17:30 UTC, TOUFIKIzakarya commented on MicrosoftActiveDirectory/tests/test_search.py
> +def test_search():
I'm not sure that this test will pass. I think you need to mock the search method.

2024-10-29 08:19 UTC, TOUFIKIzakarya approved these changes
LGFM

2024-10-29 08:23 UTC, squioc approved these changes
LGTM

2024-10-29 14:58 UTC, merged