fix(sekoia.io): fix some typing in json schema and url of get asset
SEKOIA-IO/automation-library pull request #1237
Opened 2024-12-26 10:30 UTC by ysindel

2024-12-30 09:53 UTC, TOUFIKIzakarya approved these changes
LGFM

2025-01-02 10:34 UTC, squioc requested changes
Can you bump the version number in manifest.json and add a new entry in CHANGELOG.md?

2025-01-07 09:44 UTC, TOUFIKIzakarya approved these changes
LGFM

2025-01-09 15:24 UTC, squioc approved these changes
LGTM

2025-01-09 15:25 UTC, merged