Cato SASE connector
SEKOIA-IO/automation-library pull request #151
Opened 2023-08-03 07:28 UTC by vg-svitla

2023-08-03 11:50 UTC, squioc approved these changes
:+1:

2023-08-03 11:50 UTC, squioc commented on CatoNetwork/cato/connector.py
> +            while True:
I suggest using `self.running` that is False when the connector should end.
```suggestion
            while self.running:
```

2023-08-03 11:52 UTC, squioc requested changes

2023-08-03 11:52 UTC, squioc commented on CatoNetwork/cato/connector.py
Could you change the name of this file for something more explict? like `connector_sase_events.py'?

2023-08-03 16:50 UTC, squioc commented on CatoNetwork/CHANGELOG.md
> +### 2023-06-13 - 1.0.0
Are you sure about the date?

2023-08-04 07:19 UTC, vg-svitla commented on CatoNetwork/CHANGELOG.md
> +### 2023-06-13 - 1.0.0
Fixed thank you!

2023-08-11 14:58 UTC, Adamowoc approved these changes
LGTM

2023-08-18 09:34 UTC, merged