Improve/feedtriggersymphony
SEKOIA-IO/automation-library pull request #262
Opened 2023-09-20 15:23 UTC by rombernier

- [ ]  Refresh more frequently
- [ ]  Use files to transfer data to actions instead of parameters
- [ ]  Get revoked objects after first complete run

2023-09-21 15:21 UTC, Darkheir requested changes
Those changes in the trigger will break existing playbooks.

To make the change with breaking we must introduce a new attribute `to_file` that should be false by default allowing the user to choose how to sync the data.

Also your limit to 2000 will break existing playbooks because the size of the event will be too big to be processed by actions.

Finally the version in the manifest should be bumped.

2023-09-21 15:21 UTC, Darkheir commented on Sekoia.io/sekoiaio/triggers/intelligence.py
> +                return f"{url}&cursor={cursor}&include_revoked=true"
This will include the revoked indicator not after the first full sync but after we fetch the first page.

2023-09-21 15:21 UTC, Darkheir commented on Sekoia.io/sekoiaio/triggers/intelligence.py
>              )
This is a breaking change that will break all the existing playbooks expecting to find a `stix_objects` attribute and not a path

2023-09-21 15:21 UTC, Darkheir commented on Sekoia.io/sekoiaio/triggers/intelligence.py
> +            file_path = str(stix_objects_path.relative_to(work_dir))
In the SDK there is an helper `storage.write` doing that.

2023-09-22 06:56 UTC, Darkheir commented
> Thanks for your review, I will make the changes, what is the size limit of event to be processed by actions ?

I think that  if the client wants to write it in a file you can set the limit to 2000 else keep it at 200

2023-09-26 06:42 UTC, Darkheir requested changes
The version in the module manifest must also be bumped

2023-09-26 06:42 UTC, Darkheir commented on CrowdStrikeFalcon/crowdstrike_falcon/custom_iocs.py
> +        if "file_path" in arguments:
The action never expects a `file_path` arguments. The action manifest should be updated to have:

* a `stix_objects_path` arguments
* Either `stix_objects` or `stix_objects_path` required

Then replacing `stix_objects = arguments.get("stix_objects", [])` with `stix_objects = self.json_argument("stix_objects", arguments)` will be enough to look inside the file or the argument.

The version in the manifest must also be bumped

2023-09-26 06:42 UTC, Darkheir commented on Sekoia.io/sekoiaio/triggers/intelligence.py
> +    @property
You must update the trigger manifest to include the `to_file` argument

2023-09-26 06:42 UTC, Darkheir commented on Sekoia.io/sekoiaio/triggers/intelligence.py
> +            return url_batch_size_limit
```suggestion
        return 2000 if self.to_file else 200
```

2023-09-26 06:42 UTC, Darkheir commented on Sekoia.io/sekoiaio/triggers/intelligence.py
> +                    event_name=event_name, event={"file_path": filepath}, directory=directory, remove_directory=True
The convention is to use the same name as for when it is not in a file with the `_path` suffix.

```suggestion
                    event_name=event_name, event={"stix_objects_path": filepath}, directory=directory, remove_directory=True
```

You must also update the trigger manifest to add this attribute as a result

2023-09-26 14:02 UTC, rombernier commented
Hello @Darkheir, I didn't forget to bump the manifest version this time. I bump the middle number as it is a new functionality and not a bugfix (#sumver) , can you check the PR once more ? Thanks

2023-09-27 09:10 UTC, Darkheir approved these changes
Code looks good to me.

@squioc Do you want someone from your team to also validate the PR ?

2023-10-02 09:46 UTC, rombernier commented
Hello @squioc, can you look and validate this PR, to be able to check on test app ? Thanks

2023-10-02 10:26 UTC, squioc approved these changes
LGTM

2023-10-02 11:27 UTC, rombernier commented
Thanks for the review @squioc, do you have a trick to merge PR with check stuck in status in progress or codecov failed ?

2023-10-02 11:56 UTC, merged

2023-10-04 13:36 UTC, rombernier commented
Hello @Darkheir the build of this PR merge failed on Test module CrowdStrikeFalcon on mypy step : https://github.com/SEKOIA-IO/automation-library/actions/runs/6379736513/job/17386346337
but the test on the branch where fine, do you know if there is an issue that can create this problem ? I need to create an other PR to fix this ? Thanks

2023-10-04 14:13 UTC, Darkheir commented
@rombernier This is not a big issue, just a typing one. 

Instead of `def get_retry_after(self, response: HTTPResponse) -> float | None:` the method should have the following signature `def get_retry_after(self, response: BaseHTTPResponse) -> float | None:`.

IMO You can leave it as it is