dstny_add_getcurrenttime_module
SEKOIA-IO/automation-library pull request #372
Opened 2023-10-19 12:03 UTC by soc-dstny

add a module to get the current time

2023-10-23 15:57 UTC, squioc requested changes
Thanks for your contribution. In order to mutualize modules, can you move your action into the [Utils module](https://github.com/SEKOIA-IO/automation-library/tree/main/Utils)?
Thanks

2023-10-27 07:27 UTC, squioc approved these changes

2023-10-31 09:33 UTC, soc-dstny commented
Hello, are you missing any information for the test workflow to be launched?

2023-11-02 13:35 UTC, squioc approved these changes

2023-11-02 13:35 UTC, merged

2023-11-15 10:28 UTC, squioc commented
This action is now in production. Some changes were applied to the action.