Add password generator action
SEKOIA-IO/automation-library pull request #648
Opened 2023-12-20 15:17 UTC by TonioRyo

Add an action to generate securely a password during a playbook run to use with Entra ID and Active Directory password reset actions

2023-12-20 15:55 UTC, squioc requested changes
Thanks for the action.
Can you move this action to the automation module [utils](https://github.com/SEKOIA-IO/automation-library/tree/main/Utils), that is more suitable for this kind of actions?

2023-12-20 16:09 UTC, Darkheir requested changes

2023-12-20 16:09 UTC, Darkheir commented on Utils/utils/password_generator.py
> +        number_of_special_characters = self.json_argument("number_of_special_characters", arguments)
No need to fetch it from a file also setting defaults would be nice
```suggestion
        password_length = arguments.get("password_length", 20)
        number_of_digits = arguments.get("number_of_digits", 1)
        number_of_special_characters = arguments.get("number_of_special_characters", 1)
```

2023-12-20 16:09 UTC, Darkheir commented on Utils/utils/password_generator.py
> +        number_of_special_characters = self.json_argument("number_of_special_characters", arguments)
We also need to make sure that `number_of_digits` + `number_of_special_characters` < `password_length`

2023-12-20 16:09 UTC, Darkheir commented on Utils/utils/password_generator.py
> +                break
This method is not efficient, especially when `number_of_special_characters` or `number_of_digits` are getting close to `password_length`
```suggestion
        chars = [secrets.choice(special_chars) for _ in range(number_of_special_characters)]  # n special chars
        chars += [secrets.choice(digits) for _ in range(number_of_digits)] # n digits
        chars += [secrets.choice(alphabet) for _ in range(password_length - num_special - num_digits)]  # fill remaining with random
        random.shuffle(chars)  # Shuffle it so char and digits are not always at the beginning
        password = "".join(chars)
```

2023-12-21 08:25 UTC, Darkheir requested changes
Minor changes but code logic sounds good to me :-)

2023-12-21 08:25 UTC, Darkheir commented on Utils/action_password_generator.json
> +        ]
Not required anymore :-)

```suggestion
```

2023-12-21 08:25 UTC, Darkheir commented on Utils/utils/password_generator.py
> +            raise ValueError("number_of_digits + number_of_special_characters must be lower than password_length")
Raising an exception will result in having the errors message `An unexpected error occured: ...`.

```suggestion
            self.error("number_of_digits + number_of_special_characters must be lower than password_length")
            return
```

2023-12-21 08:25 UTC, Darkheir commented on Utils/tests/test_password_generator.py
> +        assert "number_of_digits + number_of_special_characters must be lower than password_length" in str(e)
```suggestion
    action.run(arguments_failure)
    assert action._error == "number_of_digits + number_of_special_characters must be lower than password_length"
```

2023-12-21 09:34 UTC, Darkheir approved these changes

2024-01-03 07:49 UTC, squioc approved these changes

2024-01-03 07:49 UTC, merged