Fix on pagination
SEKOIA-IO/automation-library pull request #893
Opened 2024-03-12 09:29 UTC by LenaigKaliou

2024-03-13 16:49 UTC, TOUFIKIzakarya submitted a review, later dismissed
Thanks lenaïg, this's a little remarks and also I suggest having different logs for the two methods `get_next_events` and `get_response_by_timestamp`. Like `Request on Lacework Central API to fetch next page events failed with` for `get_next_events`

2024-03-13 16:49 UTC, TOUFIKIzakarya commented on Lacework/lacework_module/lacework_connector.py
> +        self.context = PersistentJSON("context.json", "./")
```suggestion
        self.context = PersistentJSON("context.json", self._data_path)
```

2024-03-14 09:39 UTC, TOUFIKIzakarya approved these changes
LGFM

2024-03-14 10:34 UTC, squioc requested changes
Thanks for the fixes.
Still some changes to apply

2024-03-14 10:34 UTC, squioc commented on Lacework/lacework_module/lacework_connector.py
> +            cache["timestamp_cursor"] = self.from_date
The getter gets its value from the key `most_recent_date_seen` in the cache
```suggestion
            cache["most_recent_date_seen"] = self.from_date
```

2024-03-14 10:34 UTC, squioc commented on Lacework/lacework_module/lacework_connector.py
> +                    grouped_data.extend(next_page_items)
We have to compute the lag for each batch
```suggestion
                    grouped_data.extend(next_page_items)
                     last_date = self._get_most_recent_timestamp_from_items(next_page_items)
                    events_lag = int(time.time() - last_date)
                    EVENTS_LAG.labels(intake_key=self.configuration.intake_key).set(events_lag)
                    self.most_recent_date_seen = last_date
```

2024-03-14 10:34 UTC, squioc commented on Lacework/lacework_module/lacework_connector.py
> +            self.most_recent_date_seen = now
`most_recent_date_seen` must host the most recent date seen in the events. I suggest changing the way to value this property
```suggestion
```

2024-03-14 10:34 UTC, squioc commented on Lacework/lacework_module/lacework_connector.py
> +            EVENTS_LAG.labels(intake_key=self.configuration.intake_key).set(events_lag)
I suggest saving the most recent date seen here for the first batch
```suggestion
            EVENTS_LAG.labels(intake_key=self.configuration.intake_key).set(events_lag)
            self.most_recent_date_seen = last_date
```

2024-03-14 10:34 UTC, squioc commented on Lacework/lacework_module/lacework_connector.py
> +        self.from_date = recent_date
`from_date` must be the greatest date seen. Add a comparison to only save increasing dates
```suggestion
        # save the greatest date
        if self.from_date < recent_date:
                self.from_date = recent_date
```

2024-03-14 10:34 UTC, squioc commented on Lacework/lacework_module/lacework_connector.py
> +        now = datetime.now(timezone.utc)
Not sure that it's still used according to the suggestions!?
```suggestion
```

2024-03-15 15:42 UTC, squioc approved these changes
LGTM

2024-03-25 10:13 UTC, squioc requested changes
Some changes to apply.

2024-03-25 14:28 UTC, squioc submitted a review, later dismissed
Still a little change to apply

2024-03-25 14:28 UTC, squioc commented on Lacework/lacework_module/lacework_connector.py
> +            self.from_date = str(recent_date)
To represent a datetime as a string, it's preferable to use [`isoformat`](https://docs.python.org/3/library/datetime.html#datetime.datetime.isoformat):
```suggestion
            self.from_date = recent_date.isoformat()
```

2024-03-25 14:50 UTC, squioc approved these changes
LGTM

2024-03-25 14:51 UTC, merged