Feature: Azure Network Watcher
SEKOIA-IO/automation-library pull request #898
Opened 2024-03-15 08:32 UTC by vg-svitla

2024-03-15 14:32 UTC, squioc requested changes
Thanks for the PR.
Some changes to apply

2024-03-15 14:32 UTC, squioc commented on Azure/connectors/azure_blob.py
> +        return result
The content of the blob file can be textual. I suggest removing this part:
```suggestion
```

2024-03-15 14:32 UTC, squioc commented on Azure/connectors/azure_blob.py
> +        )
according to the previous comment:
```suggestion
        result: list[str] = await self.push_data_to_intakes(events=records)
```

2024-03-15 14:32 UTC, squioc commented on Azure/trigger_azure_blob_storage_events.json
Can you transfer the uuid of this manifest to the `trigger_azure_network_watcher_collector.json` and change the one here? or reverse the identifier of the two manifests in order that the existing connector are associated to Azure Network Watcher? Do the name in the `connector_*` manifest. Thanks

2024-03-19 07:54 UTC, vg-svitla commented on Azure/connectors/azure_blob.py
> +                    records.extend(self.filter_blob_data(orjson.loads(content), self.last_event_date))
I just think we can split by `\n` the content. Otherwise we will push entire file content as 1 event

2024-03-21 10:50 UTC, rombernier commented
Hello, can you merge this fix soon?, it's requested by the client https://github.com/SekoiaLab/platform/issues/53514 Thanks

2024-03-21 13:45 UTC, Adamowoc requested changes
Do not forget to update the CHANGELOG.md

2024-03-21 13:45 UTC, Adamowoc commented on Azure/connector_azure_network_watcher_collector.json
> +  "uuid": "3e5ff414-f54a-4c3e-8127-82177b31e3c4"
```suggestion
  "uuid": "626f4d84-5ab7-11ee-8c99-0242ac120002"
```
Azure network watcher should take the old uuid of Azure blob storage

2024-03-21 13:45 UTC, Adamowoc commented on Azure/trigger_azure_network_watcher_collector.json
> +    "uuid": "3e5ff414-f54a-4c3e-8127-82177b31e3c4"
```suggestion
    "uuid": "626f4d84-5ab7-11ee-8c99-0242ac120002"
```
Same here

2024-03-21 13:45 UTC, Adamowoc commented on Azure/connector_azure_blob_storage_events.json
>    "uuid": "626f4d84-5ab7-11ee-8c99-0242ac120002"
Azure blob storage needs a new uuid

2024-03-21 13:45 UTC, Adamowoc commented on Azure/trigger_azure_blob_storage_events.json
>      "results": {
modify the new uuid of Azure blob storage in this file too

2024-03-22 09:05 UTC, Adamowoc requested changes

2024-03-25 10:06 UTC, squioc approved these changes

2024-03-25 10:12 UTC, Adamowoc approved these changes

2024-03-25 10:12 UTC, merged