Update some functions and add result fields
SEKOIA-IO/automation-library pull request #940
Opened 2024-05-07 15:28 UTC by TOUFIKIzakarya

2024-05-16 13:17 UTC, squioc requested changes
Thanks for the fixes. Some changes to apply

2024-05-16 13:17 UTC, squioc commented on WithSecure/withsecure/isolate_device_from_network_action.py
> +            multistatus=response.get("multistatus"), transactionId=response.get("transactionId")
As the properties cannot be null
```suggestion
            multistatus=response.get("multistatus", []), transactionId=response["transactionId"]
```

2024-05-16 13:17 UTC, squioc commented on WithSecure/withsecure/isolate_device_from_network_action.py
> +    transactionId: str
I suggest outsourcing this declaration in a `models.py` file and import it in this file.

2024-05-16 13:17 UTC, squioc commented on WithSecure/withsecure/release_device_from_network_isolation_action.py
> +    transactionId: str
Same as above

2024-05-17 13:33 UTC, squioc approved these changes
LGTM. Just a question about the way to load the list of Detections.

2024-05-21 09:14 UTC, TOUFIKIzakarya commented on WithSecure/withsecure/list_detections_for_incident.py
> +        return DetectionItems(detections=detections)
As `model_validate` was introduced in pydantic V2. So I think we can't use it.

2024-05-21 09:16 UTC, merged